### ISSUE TITLE
Clarify build number in commit message

### ISSUE THREAD

**Issue by allthingsthursday** [mike-rogers/rally-plugin#1]
Currently, the plug-in adds the commit message to the "Message" field in the Rally changeset like this:

"blah blah blah my boring commit message blah blah blah (10)" 

where "(10)" is the build number.

I would much rather see "blah blah blah my boring commit message blah blah blah (Build # 10)" for clarity.

**Comment by mike-rogers** [comment]
It may be cool to make that a link back to the build, if that's possible. I'll look into it.

**Comment by mike-rogers** [comment]
I'm calling this one done. It's in `master` and is awaiting review/release.
